"""created user and report model

Revision ID: 396902606c69
Revises: 
Create Date: 2026-02-05 03:38:52.872596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '396902606c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('barangay_complainant', sa.String(length=100), nullable=False),
    sa.Column('contact_num', sa.String(length=13), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'agent', name='user_roles'), nullable=False),
    sa.Column('id_type', sa.String(length=50), nullable=True),
    sa.Column('id_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_num')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_name', sa.String(length=255), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('complainant_brgy', sa.String(length=100), nullable=False),
    sa.Column('incident_brgy', sa.String(length=100), nullable=False),
    sa.Column('reporter_type', sa.Enum('victim', 'witness', name='reporter_types'), nullable=False),
    sa.Column('incident_type', sa.Enum('Physical Abuse', 'Verbal Abuse', 'Sexual Harassment', 'Child Abuse', name='incident_types'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('unopened', 'viewed', 'pending', 'resolved', name='report_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('evidences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('users')
    # ### end Alembic commands ###
